development:
  adapter: sqlite3
  database: db/development.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production: 
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URI'] %>
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: database.db
